package dawidkapica.pracadyplomowa.sportapp.service;

import dawidkapica.pracadyplomowa.sportapp.coreLibrary.SpecificationCrudServiceInterface;
import dawidkapica.pracadyplomowa.sportapp.dto.ExpertSpecialisationDto;
import dawidkapica.pracadyplomowa.sportapp.entities.ExpertSpecialisationEntity;

public interface ExpertSpecialisationService extends SpecificationCrudServiceInterface<ExpertSpecialisationDto, ExpertSpecialisationEntity, Integer> {
}
