package dawidkapica.pracadyplomowa.sportapp.service;

import dawidkapica.pracadyplomowa.sportapp.coreLibrary.SpecificationCrudServiceInterface;
import dawidkapica.pracadyplomowa.sportapp.dto.NutritionalProductDto;
import dawidkapica.pracadyplomowa.sportapp.entities.NutritionalProductEntity;

public interface NutritionalProductService extends SpecificationCrudServiceInterface<NutritionalProductDto, NutritionalProductEntity, Integer> {
}
